---
  - name: create jenkins job - my_first_jenkins_job
    jenkins_job:
      config: "{{ lookup('template', 'templates/config.xml.j2') }}"
      name: my_first_jenkins_job
      url: "http://140.112.20.48:8080"
      user: admin
      password: qwerqwer
    notify:
      - restart jenkins
