---
# tasks file for rpi-boot-config
- name: restart machine
  shell: sleep 2 && shutdown -r now "/boot/config.txt config changed"
  async: 1
  poll: 0
  ignore_errors: true


- name: waiting for machine to come back
  local_action: wait_for port=22 host="{{ ansible_host|default(inventory_hostname) }}" delay=20 timeout=120
  become: false
  when: _boot_config.changed or _boot_config_lines.changed
